<form id="mainform" action="">

<?php if($this->user->getIsSuperAdmin()): ?>
<ul class="folder-actions">
    <li class="add"><a href="<?= $this->escape($this->url(array(), 'admin_create_user'));?>">Add new user</a></li>
</ul>
<?php endif; ?>

<?php if($this->users): ?>
   
    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
        <tr>
	        <th class="table-header-repeat line-left minwidth-1">Email</th>
	        <th class="table-header-options line-left"><a href="">Options</a></th>
        </tr>

        <?php foreach($this->users as $user):?>
        <tr class="alternate-row">
	        <td><?= $this->escape($user->getEmail()); ?></td>
	        <td class="options-width">
                <?php if($this->user->getIsSuperAdmin()): ?>
                    <a href="#" id="user-delete-<?= $this->escape($user->getId()) ?>" title="Delete" class="icon-2 info-tooltip user-delete"></a>
                <?php endif; ?>            
                <?php if($this->user->getIsSuperAdmin() || $this->user->getId() == $user->getId()): ?>
                    <a href="<?= $this->escape($this->url(array('user_id'=>$user->getId()), 'admin_edit_user')); ?>" id="user-edit-<?= $this->escape($user->getId()) ?>" title="Edit" class="icon-1 info-tooltip"></a>
                <?php endif; ?>            
            </td>
        </tr>
        <?php endforeach; ?>
    </table>

<?php else: ?>
    <p>There are currently no users.</p>
<?php endif; ?>

<?php if($this->user->getIsSuperAdmin()): ?>
<ul class="folder-actions">
    <li class="add"><a href="<?=$this->escape($this->url(array(), 'admin_create_user'));?>">Add new user</a></li>
</ul>
<?php endif; ?>

</form>
</div>
<script type="text/javascript">
    $(document).ready(
        function()
        {
            $('.user-delete').ajaxDeleter(<?= json_encode($this->url(array('user_id' => 'xxx'), 'admin_delete_user')) ?>);        
        }
    );
</script>
