<?php

namespace EasyCMS\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class App_Model_FolderProxy extends \App_Model_Folder implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getSubFolders()
    {
        $this->__load();
        return parent::getSubFolders();
    }

    public function addToSubFolders(\App_Model_Folder $folder)
    {
        $this->__load();
        return parent::addToSubFolders($folder);
    }

    public function addToPages(\App_Model_Page $page)
    {
        $this->__load();
        return parent::addToPages($page);
    }

    public function getPages()
    {
        $this->__load();
        return parent::getPages();
    }

    public function addToFiles(\App_Model_File $file)
    {
        $this->__load();
        return parent::addToFiles($file);
    }

    public function getFiles()
    {
        $this->__load();
        return parent::getFiles();
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent(\App_Model_Folder $parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'subFolders', 'pages', 'files', 'parent_id', 'parent');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}